### ISSUE TITLE
NC3003: Duplicate method key: transfer,4.

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-devpack-dotnet#825]
compile https://github.com/neoburger/code/blob/main/BurgerNEO.cs and u get this error on new version of nccs.

C:\Users\Chris\Projects\code\BurgerNEO\BurgerNEO.cs(91,28): error NC3003: Duplicate method key: transfer,4.

This can compile on dotnet 5 nccs 3.0.3

**Comment by Hecate2** [comment]
In `neo-devpack-dotnet\src\Neo.Compiler.CSharp\CompilationContext.cs`, comment out the if clause near line 500:
```csharp
                //if (methodsExported.Any(u => u.Name == method.Name && u.Parameters.Length == method.Parameters.Length))
                //    throw new CompilationException(symbol, DiagnosticId.MethodNameConflict, $"Duplicate method key: {method.Name},{method.Parameters.Length}.");
```
Then the compilation will succeed, but there will be two transfer methods in the manifest. You can delete the first transfer method. And if you want to skip the step of modifying the manifest...
```csharp
                //if (methodsExported.Any(u => u.Name == method.Name && u.Parameters.Length == method.Parameters.Length))
                //    throw new CompilationException(symbol, DiagnosticId.MethodNameConflict, $"Duplicate method key: {method.Name},{method.Parameters.Length}.");
                AbiMethod? foundMethod = methodsExported.Where(u => u.Name == method.Name && u.Parameters.Length == method.Parameters.Length).FirstOrDefault();
                if (foundMethod is not null)
                    methodsExported.Remove(foundMethod);
                methodsExported.Add(method);
```
Then just compile with the modified compiler, and just deploy the nef

**Comment by Hecate2** [comment]
[neoburger-code-new.zip](https://github.com/neo-project/neo-devpack-dotnet/files/13578841/neoburger-code-new.zip)
Here are the compiled results

**Comment by Hecate2** [comment]
I met this issue at https://github.com/neo-project/neo-devpack-dotnet/issues/686 , long long ago...

**Comment by Liaojinghui** [comment]
close as it is not an issue of the compiler.

**Comment by Hecate2** [comment]
If this is not considered a problem, we are not allowing developers to inherit `Nep17Token` from `Neo.SmartContract.Framework`, and then `override` or write `new` methods.

**Comment by Liaojinghui** [comment]
> If this is not considered a problem, we are not allowing developers to inherit `Nep17Token` from `Neo.SmartContract.Framework`, and then `override` or write `new` methods.

I'll check
